# ===========================================
# DOCKER COMPOSE - EMAIL TO FTP SERVICE
# ===========================================

version: '3.8'

services:
  email-to-ftp-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: email-to-ftp-service
    ports:
      - "11000:11000"
    environment:
      # Configurações de ambiente
      - SPRING_PROFILES_ACTIVE=dev
      - JAVA_OPTS=-Xmx512m -Xms256m
      
      # Variáveis do host - usando ${NOME_VARIAVEL} ou ${NOME_VARIAVEL:-valor_padrao}
      - EMAIL_HOST=${EMAIL_HOST:-smtp.gmail.com}
      - EMAIL_PORT=${EMAIL_PORT:-587}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - FTP_HOST=${FTP_HOST}
      - FTP_PORT=${FTP_PORT:-21}
      - FTP_USERNAME=${FTP_USERNAME}
      - FTP_PASSWORD=${FTP_PASSWORD}
      
      # Outras variáveis do sistema (exemplos)
      - JAVA_HOME=${JAVA_HOME}
      - TZ=${TZ:-America/Sao_Paulo}
      
    volumes:
      # Volume para logs (opcional)
      - ./logs:/app/logs
      
      # Volume para arquivos de configuração externos (opcional)
      # - ./config:/app/config
      
    networks:
      - email-ftp-network
    
    # Restart policy
    restart: unless-stopped
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11000/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  email-ftp-network:
    driver: bridge

volumes:
  email-ftp-logs:
    driver: local
