version: '3.8'

services:
  monitor-email-to-ftp:
    build: .
    container_name: monitor-email-to-ftp
    ports:
      - "8081:80"  # Porta externa:interna
    environment:
      # URL da API - MODIFIQUE CONFORME NECESSÁRIO
      - API_BASE_URL=http://172.20.21.8:11000/api/v1/email-to-ftp
      
      # Ambiente
      - ENVIRONMENT=production
      
      # Intervalos de atualização (em milissegundos)
      - REFRESH_INTERVAL=30000
      - CONNECTION_TEST_INTERVAL=120000
      - SCHEDULING_UPDATE_INTERVAL=10000
    
    # Opcional: volumes para logs
    volumes:
      - ./logs:/var/log/nginx
    
    # Restart policy
    restart: unless-stopped
    
    # Networks (opcional)
    networks:
      - monitor-network

networks:
  monitor-network:
    driver: bridge
